/// <reference path="defs/require.d.ts" />
/// <reference path='defs/jquery.d.ts' />
/// <reference path='defs/angular.d.ts' />
/// <reference path="defs/restangular.d.ts" />
/// <reference path="utils/Utils.ts" />
//// <reference path="utils/Spin.ts" />
/// <reference path="utils/Toastr.ts" />
/// <reference path="utils/Noty.ts" />
/// <reference path="utils/Base64.ts" />
/// <reference path="config/Constants.ts" />
/// <reference path="utils/BreadCrumbs.ts" />
/// <reference path="config/UIRouter.ts" />
/// <reference path="config/RestangularConfig.ts" />
/// <reference path="config/LocationConfig.ts" />
///<reference path="directives/ExecuteClickOnce.ts" />
///<reference path="directives/NgSpinner.ts" />
/// <reference path="controllers/BaseCtrl.ts" />
/// <reference path="controllers/ArtistCtrl.ts" />
/// <reference path="controllers/AlbumsCtrl.ts" />
/// <reference path="controllers/TracksCtrl.ts" />
/// <reference path="controllers/ArtistFormCtrl.ts" />
/// <reference path="controllers/AlbumFormCtrl.ts" />
/// <reference path="controllers/TrackFormCtrl.ts" />
/// <reference path="services/Resource.ts" />
/// <reference path='Run.ts' />
//// <reference path='App.ts' />